/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPanelRouteImport } from './routes/_app/panel'
import { Route as AppCreateIndexRouteImport } from './routes/_app/create/index'
import { Route as AppAnimalAnimalIdRouteRouteImport } from './routes/_app/animal.$animalId/route'
import { Route as AppAnimalAnimalIdIndexRouteImport } from './routes/_app/animal.$animalId/index'
import { Route as AppAnimalAnimalIdEditRouteImport } from './routes/_app/animal.$animalId/edit'
import { Route as AppAnimalAnimalIdMedicalRecordsIndexRouteImport } from './routes/_app/animal.$animalId/medical-records/index'
import { Route as AppAnimalAnimalIdEventsIndexRouteImport } from './routes/_app/animal.$animalId/events/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPanelRoute = AppPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateIndexRoute = AppCreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnimalAnimalIdRouteRoute = AppAnimalAnimalIdRouteRouteImport.update({
  id: '/animal/$animalId',
  path: '/animal/$animalId',
  getParentRoute: () => AppRoute,
} as any)
const AppAnimalAnimalIdIndexRoute = AppAnimalAnimalIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAnimalAnimalIdRouteRoute,
} as any)
const AppAnimalAnimalIdEditRoute = AppAnimalAnimalIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppAnimalAnimalIdRouteRoute,
} as any)
const AppAnimalAnimalIdMedicalRecordsIndexRoute =
  AppAnimalAnimalIdMedicalRecordsIndexRouteImport.update({
    id: '/medical-records/',
    path: '/medical-records/',
    getParentRoute: () => AppAnimalAnimalIdRouteRoute,
  } as any)
const AppAnimalAnimalIdEventsIndexRoute =
  AppAnimalAnimalIdEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AppAnimalAnimalIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panel': typeof AppPanelRoute
  '/animal/$animalId': typeof AppAnimalAnimalIdRouteRouteWithChildren
  '/create/': typeof AppCreateIndexRoute
  '/animal/$animalId/edit': typeof AppAnimalAnimalIdEditRoute
  '/animal/$animalId/': typeof AppAnimalAnimalIdIndexRoute
  '/animal/$animalId/events/': typeof AppAnimalAnimalIdEventsIndexRoute
  '/animal/$animalId/medical-records/': typeof AppAnimalAnimalIdMedicalRecordsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/panel': typeof AppPanelRoute
  '/create': typeof AppCreateIndexRoute
  '/animal/$animalId/edit': typeof AppAnimalAnimalIdEditRoute
  '/animal/$animalId': typeof AppAnimalAnimalIdIndexRoute
  '/animal/$animalId/events': typeof AppAnimalAnimalIdEventsIndexRoute
  '/animal/$animalId/medical-records': typeof AppAnimalAnimalIdMedicalRecordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/panel': typeof AppPanelRoute
  '/_app/animal/$animalId': typeof AppAnimalAnimalIdRouteRouteWithChildren
  '/_app/create/': typeof AppCreateIndexRoute
  '/_app/animal/$animalId/edit': typeof AppAnimalAnimalIdEditRoute
  '/_app/animal/$animalId/': typeof AppAnimalAnimalIdIndexRoute
  '/_app/animal/$animalId/events/': typeof AppAnimalAnimalIdEventsIndexRoute
  '/_app/animal/$animalId/medical-records/': typeof AppAnimalAnimalIdMedicalRecordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/panel'
    | '/animal/$animalId'
    | '/create/'
    | '/animal/$animalId/edit'
    | '/animal/$animalId/'
    | '/animal/$animalId/events/'
    | '/animal/$animalId/medical-records/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/panel'
    | '/create'
    | '/animal/$animalId/edit'
    | '/animal/$animalId'
    | '/animal/$animalId/events'
    | '/animal/$animalId/medical-records'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/panel'
    | '/_app/animal/$animalId'
    | '/_app/create/'
    | '/_app/animal/$animalId/edit'
    | '/_app/animal/$animalId/'
    | '/_app/animal/$animalId/events/'
    | '/_app/animal/$animalId/medical-records/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/panel': {
      id: '/_app/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AppPanelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create/': {
      id: '/_app/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof AppCreateIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/animal/$animalId': {
      id: '/_app/animal/$animalId'
      path: '/animal/$animalId'
      fullPath: '/animal/$animalId'
      preLoaderRoute: typeof AppAnimalAnimalIdRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/animal/$animalId/': {
      id: '/_app/animal/$animalId/'
      path: '/'
      fullPath: '/animal/$animalId/'
      preLoaderRoute: typeof AppAnimalAnimalIdIndexRouteImport
      parentRoute: typeof AppAnimalAnimalIdRouteRoute
    }
    '/_app/animal/$animalId/edit': {
      id: '/_app/animal/$animalId/edit'
      path: '/edit'
      fullPath: '/animal/$animalId/edit'
      preLoaderRoute: typeof AppAnimalAnimalIdEditRouteImport
      parentRoute: typeof AppAnimalAnimalIdRouteRoute
    }
    '/_app/animal/$animalId/medical-records/': {
      id: '/_app/animal/$animalId/medical-records/'
      path: '/medical-records'
      fullPath: '/animal/$animalId/medical-records/'
      preLoaderRoute: typeof AppAnimalAnimalIdMedicalRecordsIndexRouteImport
      parentRoute: typeof AppAnimalAnimalIdRouteRoute
    }
    '/_app/animal/$animalId/events/': {
      id: '/_app/animal/$animalId/events/'
      path: '/events'
      fullPath: '/animal/$animalId/events/'
      preLoaderRoute: typeof AppAnimalAnimalIdEventsIndexRouteImport
      parentRoute: typeof AppAnimalAnimalIdRouteRoute
    }
  }
}

interface AppAnimalAnimalIdRouteRouteChildren {
  AppAnimalAnimalIdEditRoute: typeof AppAnimalAnimalIdEditRoute
  AppAnimalAnimalIdIndexRoute: typeof AppAnimalAnimalIdIndexRoute
  AppAnimalAnimalIdEventsIndexRoute: typeof AppAnimalAnimalIdEventsIndexRoute
  AppAnimalAnimalIdMedicalRecordsIndexRoute: typeof AppAnimalAnimalIdMedicalRecordsIndexRoute
}

const AppAnimalAnimalIdRouteRouteChildren: AppAnimalAnimalIdRouteRouteChildren =
  {
    AppAnimalAnimalIdEditRoute: AppAnimalAnimalIdEditRoute,
    AppAnimalAnimalIdIndexRoute: AppAnimalAnimalIdIndexRoute,
    AppAnimalAnimalIdEventsIndexRoute: AppAnimalAnimalIdEventsIndexRoute,
    AppAnimalAnimalIdMedicalRecordsIndexRoute:
      AppAnimalAnimalIdMedicalRecordsIndexRoute,
  }

const AppAnimalAnimalIdRouteRouteWithChildren =
  AppAnimalAnimalIdRouteRoute._addFileChildren(
    AppAnimalAnimalIdRouteRouteChildren,
  )

interface AppRouteChildren {
  AppPanelRoute: typeof AppPanelRoute
  AppAnimalAnimalIdRouteRoute: typeof AppAnimalAnimalIdRouteRouteWithChildren
  AppCreateIndexRoute: typeof AppCreateIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPanelRoute: AppPanelRoute,
  AppAnimalAnimalIdRouteRoute: AppAnimalAnimalIdRouteRouteWithChildren,
  AppCreateIndexRoute: AppCreateIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
